### ISSUE TITLE
One should obtain consent

### ISSUE THREAD

**Issue by kaaetech** [DarknessTomDev/RevolutInternalAPI#1]
```
[/tmp/RevolutInternalAPI/examples/SimpleApp kudahl]: NUMBER=00452XXXXXXXX PASSCODE=XXXX ts-node hello.ts
{
  message: 'One should obtain consent from the user before continuing',
  code: 9035
}
```

What would this mean?

**Comment by ShufflePerson** [comment]
Check your Revolut app, a verification is requested in order to authenticate.

**Comment by kaaetech** [comment]
> Check your Revolut app, a verification is requested in order to authenticate.

That is what I thought at first however it doesn't seem to be the case🙈

**Comment by ShufflePerson** [comment]
It's been quite a while since I worked on the project, and I no longer use Revolut.
(The source is 6+ Months old, just it was private for a long time)

Possible there has been some API change, which sadly I cannot update currently. 

If you do manage to get it working, I will be very thankful if you can share your fix here :)

**Comment by kaaetech** [comment]
How did you originally sniff the requests? I found that it has SSL Pinning on iOS whilst trying to sniff by proxy

**Comment by ShufflePerson** [comment]
The Shopper Extension. https://www.revolut.com/revolut-shopper/

The shopper extension is also the place where the encryption and decryption was reversed from, so if that is outdated you will have to update that.


Sorry for the slow response times, I am not too active on Github atm

**Comment by kaaetech** [comment]
It would seem that my lack of a KYC scheme inside the Revolut app was the reason the consent modal wasn’t appearing in the app. Your source code is still up-to-date. Thank’s for your replies!

**Comment by ShufflePerson** [comment]
Glad you got the issue sorted. If you need anything lmk!

Have a nice day.
